### ISSUE TITLE
Attaching Media 

### ISSUE THREAD

**Issue by scottiefalkon** [tooot-app/app#407] opened 2022-10-14 00:37 UTC
When tapping the icon to attach media, the dialog reappears after choosing media type, making user select type again before media picker will open.

**Comment by xmflsct** [comment] 2022-10-16 19:11
@scottiefalkon Which OS are you using? And which version of the app do you have? If you haven't updated to the latest version (v.4.3.4), can you have a try to see if the issue persists. Thanks!

**Comment by scottiefalkon** [comment] 2022-10-16 22:57
Android 13, Tooot 4.3.4

**Comment by xmflsct** [comment] 2022-10-27 21:32
Cannot reproduce in the emulator. Soon will publish an updated version and maybe you can try again in there?

**Comment by xmflsct** [comment] 2022-12-03 20:19
Will close the issue for now

**Closed by xmflsct** 2022-12-03 20:19 UTC
Labels: bug, _android
