### ISSUE TITLE
Truncated title of home screen on iOS (iPhone XR)

### ISSUE THREAD

**Issue by cmilr** [tooot-app/app#448] opened 2022-11-08 23:18 UTC
New Tooot user on iOS here. Just wanted to let you know that the title at the top of the home screen (I assume it says "Following") truncates on iPhone XR. Please let me know if there's other info I can provide to be of help.

![truncated](https://user-images.githubusercontent.com/2286876/200696152-4c0826ee-a39c-4c1d-bb42-9e1bc9890669.jpg)

**Comment by xmflsct** [comment] 2022-11-11 22:16
Hi, I cannot reproduce this issue at least in the simulator. Which iOS version are you using, and which tooot version do you have? Thanks!

**Comment by cmilr** [comment] 2022-11-14 17:14
Let's see: 
iOS v 15.6.1
Tooot v 4.5.1

**Comment by z3nitsu** [comment] 2022-11-20 04:47
Same issue on Android 
Android 12
Toot v 4.6.1

**Comment by z3nitsu** [comment] 2022-11-20 04:59
these parts of the app also have it 

![photo_2022-11-20_10-28-01](https://user-images.githubusercontent.com/59967175/202886392-2a2d6b52-da71-4c4b-aebf-fe1aef5070d0.jpg)
![photo_2022-11-20_10-28-16](https://user-images.githubusercontent.com/59967175/202886394-59e467c1-0fbb-4f09-8371-989ab379288d.jpg)

**Comment by xmflsct** [comment] 2022-12-12 23:01
Hi all, is this fixed with the latest version v4.6.6?

**Comment by xmflsct** [comment] 2022-12-18 20:41
Closing for now. If it still happens on the latest v4.7.0, feel free to reopen the issue.

**Closed by xmflsct** 2022-12-18 20:41 UTC
Labels: experience, bug, _ios

**Comment by z3nitsu** [comment] 2022-12-26 15:55
@xmflsct Hey, the issue is still there.

**Comment by xmflsct** [comment] 2022-12-27 09:53
@z3nitsu which operating system, and which version of the app you are using now?

**Comment by z3nitsu** [comment] 2022-12-27 14:21
@xmflsct Android: 12, App version: 4.7.2

**Comment by z3nitsu** [comment] 2023-01-08 15:08
@xmflsct any update?

**Comment by cmilr** [comment] 2023-01-08 16:08
Latest update fixed it for me on iPhone XR.

**Comment by xmflsct** [comment] 2023-01-08 23:53
@z3nitsu I cannot reproduce the isse. Please check again in the next release, hopefully coming in few days.

**Comment by z3nitsu** [comment] 2023-01-09 06:19
For me it is still not fixed
