### ISSUE TITLE
Boosts and favorites show as having been done by the user being boosted or favorited rather than the user who performed the action

### ISSUE THREAD

**Issue by thebishopgame** [tooot-app/app#516] opened 2022-12-05 14:26 UTC
On iOS 4.6.5, if user X boosts user Y’s post, the text will read as “Y boosted (Y’s toot)” rather than “X boosted (Y’s toot)”. With favorites, my notification screen looks as if I had favorited my own toots a bunch of times.

**Comment by xmflsct** [comment] 2022-12-05 14:47
Duplicate of https://github.com/tooot-app/app/issues/514, fixed in https://github.com/tooot-app/app/commit/c6e27d6d8845ffd35be26923851d80c04920fccb

**Closed by xmflsct** 2022-12-05 14:47 UTC
