### ISSUE TITLE
Notifications: Favorites says I liked my own post. 

### ISSUE THREAD

**Issue by kbexit** [tooot-app/app#522] opened 2022-12-05 19:22 UTC
As title states and I don't like my own posts lol.![Screenshot_20221205-142011.png](https://user-images.githubusercontent.com/102698001/205724570-c35deaf4-b28c-4bba-b764-bb18e3f4693a.png)

**Comment by xmflsct** [comment] 2022-12-05 20:25
Duplicate of https://github.com/tooot-app/app/issues/514, fixed in https://github.com/tooot-app/app/commit/c6e27d6d8845ffd35be26923851d80c04920fccb

**Closed by xmflsct** 2022-12-05 20:25 UTC
Labels: duplicate

**Comment by kbexit** [comment] 2022-12-05 20:28
Interesting because... I just updated to the latest update in the play store and have it this way, as the previous version didn't have this issue...

**Comment by xmflsct** [comment] 2022-12-05 20:31
No you are right. I am fixing this as we speak, therefore closing for duplicate reports.

**Comment by kbexit** [comment] 2022-12-06 02:06
> No you are right. I am fixing this as we speak, therefore closing for duplicate reports.

Just got the new update on the play store and so far so good. Thank you 🙏
