### ISSUE TITLE
Blank screen when tapping on a notification from a different account

### ISSUE THREAD

**Issue by limdingwen** [tooot-app/app#414] opened 2022-10-25 07:33 UTC
# Steps to reproduce:

1. Have two accounts.
2. Go into account A.
3. Go back to the home screen.
4. Get a notification from account B; for example, a new post mentioning you.
5. Tap the notification.

# What happened?

The screen goes blank and does not respond. After force-restarting the app, I think it was in account B.

# What should happen?

The app switches to account B and goes to the post that was in the notification.

# System

iOS v16.0.3 on iPhone SE
tooot v4.3.4 from App Store
Outside China

**Comment by xmflsct** [comment] 2022-10-27 21:19
hmmm, unfortunately I cannot reproduce this behaviour. Are you referring to tapping on the message when the app is open (in the foreground), is that correct? Can you maybe try few more times?

**Comment by xmflsct** [comment] 2022-12-03 20:23
Will close this issue for now

**Closed by xmflsct** 2022-12-03 20:23 UTC
Labels: bug
